supported_extension = {
    '.bash': 'shell',
    '.bat': 'batch',
    '.c': 'c',
    '.cc': 'cpp',
    '.cmake': 'cmake',
    '.cmd': 'shell',
    '.cpp': 'cpp',
    '.cs': 'csharp',
    '.cxx': 'cpp',
    '.go': 'go',
    '.h': 'c',
    '.hpp': 'cpp',
    '.js': 'javascript',
    '.java': 'java',
    '.kt': 'kotlin',
    '.kts': 'kotlin',
    '.m': 'matlab',
    '.php': 'php',
    '.ps1': 'powershell',
    '.py': 'python',
    '.rb': 'ruby',
    '.rs': 'rust',
    '.sh': 'shell',
    '.sql': 'sql',
    '.ts': 'typescript',
    '.vue': 'vue',
}
